/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../cv_pnp.h"
/* Header for class top_nowandfuture_CVPnP */

#ifndef _Included_top_nowandfuture_jmediapipe_CVPnP
#define _Included_top_nowandfuture_jmediapipe_CVPnP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_nowandfuture_CVPnP
 * Method:    solvePnP
 * Signature: ([D[D[D[D[D[DBI)V
 */
JNIEXPORT void JNICALL Java_top_nowandfuture_jmediapipe_CVPnP_solvePnP
  (JNIEnv *, jclass, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jdoubleArray, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
